### PR TITLE
task 1 completed

### PR DESCRIPTION
**Pull request by s4il3sh**

### CODE REVIEW

**Comment by uarif** [comment]
Your code does not work.

**Comment by uarif** [comment]
I believe It's because, you imported the module but It's not there., Ca you please double-check? Thank you

**Comment by s4il3sh** [comment]
@uarif It does work. But let me add fft work in it too. I think we need to do it via fft code.

**Comment by uarif** [comment]
I can merge your code, you can do changes later. And also, dont you need to plot it as well?

**Pull request merged**
